### ISSUE TITLE
Data dump link still limited to an hour

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1308] opened 2015-08-26 07:38 UTC
I tried to download the csv after an hour and the link was invalid:

<Message>Request has expired</Message><Expires>2015-08-26T07:13:23Z</Expires><ServerTime>2015-08-26T07:36:05Z</ServerTime>

**Comment by camallen** [comment] 2015-08-26 08:12
Duplicate of #1204 - @mschwamb can you PM me the email you got?

**Closed by camallen** 2015-08-26 08:12 UTC
