### ISSUE TITLE
Incorrect HTTP response code when headers are missing

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes#1606] opened 2016-01-12 16:23 UTC
When querying the Panoptes API, as we know the headers
```
Accept:application/vnd.api+json; version=1
Content-Type:application/json
```
need to be specified.

However if you miss them off, it gives 404 NOT FOUND. Which as far as HTTP status codes go, is quite inaccurate.

The response should probably be 415 UNSUPPORTED MEDIA TYPE - see http://stackoverflow.com/questions/11461037/appropriate-http-status-code-for-request-specifying-invalid-content-encoding-hea for discussion of this.

List of HTTP status codes: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by camallen** [comment] 2016-01-12 16:47
that media type is supported but that route isn't so it's a 404, from memory. We have a bunch of normal `text/html` routes that this request could be matching.

**Comment by camallen** [comment] 2016-03-22 08:46
closing this since it's expected behaviour for the requested media type.

**Closed by camallen** 2016-03-22 08:46 UTC
