### ISSUE TITLE
Living Sailor uses 2MB subject images

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/panoptes#4337] opened 2024-05-25 12:17 UTC
Subject images are ~2MB each, leading to slow downloads and large data requirements for volunteers. 

The images are externally hosted, so outside Zooniverse control, but maybe the lab could warn project owners about excessively large subject images. 

Perhaps projects could also warn volunteers, particularly those on phones and tablets, when classifying requires a large amount of bandwidth. 

A typical Living Sailor subject: https://inaturalist-open-data.s3.amazonaws.com/photos/22120312/original.jpeg

![A 2MB subject image.](https://inaturalist-open-data.s3.amazonaws.com/photos/22120312/original.jpeg)

Project home page: https://www.zooniverse.org/projects/rebeccarhelm/the-living-sailor

**Comment by lcjohnso** [comment] 2024-05-28 18:56
Hi @eatyourgreens @goplayoutside3 -- I transferred this issue over to Panoptes, as the easiest solution would be to change the default image used by the iNat Importer (used for the Living Sailor subject above) from `original.jpeg` to `large.jpeg`. Before we proceed, we are checking with iNat folks because originally there was uncertainty whether all image sizes were available for all taxonomy choices (might only be guaranteed to have `original` and `square`, which is a thumbnail preview size).  Zach and I are picking this up now; thanks for opening, @eatyourgreens.

**Comment by eatyourgreens** [comment] 2024-05-29 08:52
Thanks! The IIIF importer has the same problem. Most IIIF providers forbid access to the full size image, so I set an arbitrary subject image size that's supported by most British Library collections. The downside of that choice was that it's possible to import a manifest and get broken image URLs, depending on the provider. The Readme has a bit more detail about how those images work, but the image sizing is basically configured in the URL. 

https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/pages/lab/iiif

**Comment by lcjohnso** [comment] 2024-06-19 19:41
iNat confirmed that large.jpeg is available for all images, so @zwolf will make the change to use that image size as default within the iNat Importer.

**Closed** 2024-07-18 15:45 UTC
