### ISSUE TITLE
out of data message didn't show up on Comet Hunters

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1745] opened 2016-03-26 19:35 UTC
We just ran out of data on Comet Hunters. The project launched at the end of December. My understanding is that it shouldn't have the same counters issue as Planet Four: Terrains does. Is that correct?  I thought I'd mention it in case there was a different new issue that prevents the out of data message for going up.

**Comment by alexbfree** [comment] 2016-03-31 08:26
Also experiencing this issue with https://www.zooniverse.org/projects/alexbfree/snapshot-serengeti-computer-vision/ - all subjects have been retired but it's not showing Out of Data

**Comment by camallen** [comment] 2016-04-13 15:38
this is aduplicate of #1571

**Closed** 2016-08-21 21:40 UTC
