### ISSUE TITLE
Unable to get classifications

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1204] opened 2015-07-28 16:07 UTC
@edpaget, maybe you're in the midst of working on this, but I requested classifications for project 347 between 1 and 2 hours ago. When I click on the link on the project builder, I get an XML error page, rather than my most recent classifications data. (Same thing happens in project 348.)

**Comment by camallen** [comment] 2015-07-29 12:55
@mkosmala was this the first time you'd ever requested data like this? I assume that those links point to an empty resource url if the data hadn't been uploaded yet.

**Comment by mkosmala** [comment] 2015-07-29 13:49
No, that's what I found weird. I first requested the data a week ago, and got it fine. Then yesterday, I requested again. I was able to get the data for project 348 because I got to the link within the hour window. I hadn't gotten an email about 347 yet, but tried its link anyway, and got the data from a week ago. Fine. So I waited some more and did some other stuff and missed the hour window for 347. When I went to its link between 1 and 2 hours after the export was ready, I got the XML error. I then tried 348 for comparison, and also got the XML error there. Seemed wonky, so I made an issue and haven't requested data since.

**Comment by mkosmala** [comment] 2015-07-29 13:51
The request you made today seems to work fine, though. I was just able to retrieve the data you requested. 

Oh, also, after I got the XML error, I tried refreshing the browser page when I was on the project page, but didn't go so far as to clear the cache. Not sure if any of that matters, but there it is.

**Comment by camallen** [comment] 2015-07-29 15:05
Ok - leaving this open at the moment. Links are working ok for me and should be valid. May be a cached resource issue on media controller so the links don't get the new get expiration value.

**Comment by mkosmala** [comment] 2015-07-29 15:11
Ok. I'll let you know if I run into this problem again.

**Comment by bruggsy** [comment] 2015-07-29 18:30
Hi, I'm actually having the same issue, but I get an XML error every time I request any classifications. When I use the project builder page "request classifications report" and open the link I receive via email, I get an xml error page with a "Signature Does Not Match" error. This happens for the subject report as well; I've never been able to get any results through the project builder page. The project # is 292, let me know if you need any more info!

**Comment by tedcheese** [comment] 2015-07-29 18:41
I had a somewhat similar issue; does the link in the project details page work, under Data Export:
"Request new classification export CSV format. Most recent data available requested 2 minutes ago."

the "2 minutes ago" should take you to your data. Always give it a minute once requested

**Comment by bruggsy** [comment] 2015-07-29 18:42
Yeah, I just tried that and got the data no problem. Thanks!

**Comment by mkosmala** [comment] 2015-07-29 18:43
@tedcheese It's a little weird right now. It will say "Most recent data available requested 2 minutes ago" even if the data isn't yet ready. Once the data is available, you get emailed (to the address associated with your Zooniverse login) and the project builder link resets its time to when the export became available.

**Comment by mkosmala** [comment] 2015-07-29 18:43
@tedcheese @bruggsy PS. Data export is rather slow right now. Unless you have only a handful of classifications, expect to wait 15-30 minutes or more.

**Comment by camallen** [comment] 2015-08-17 10:29
This is hard to debug as we need to reproduce the invalid url to debug. If you keep experiencing this, please ping this issue so we can get the invalid (don't post it here) of you via PM.

Also @mkosmala data dumps are somewhat slow as we are doing a lot of data processing (joins) for research teams. The more we put into these files the slower they become to create.

**Comment by tedcheese** [comment] 2015-08-17 17:39
Thanks. The issue is not a major one for us. Cheers, Ted — Whales as Individuals



> On Aug 17, 2015, at 10:29 PM, Campbell Allen <notifications@github.com> wrote:
> 
> This is hard to debug as we need to reproduce the invalid url to debug. If you keep experiencing this, please ping this issue so we can get the invalid (don't post it here) of you via PM.
> 
> Also @mkosmala <https://github.com/mkosmala> data dumps are somewhat slow as we are doing a lot of data processing (joins) for research teams. The more we put into these files the slower they become to create.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/zooniverse/Panoptes/issues/1204#issuecomment-131770292>.
> 


—
Have you walked among 100,000 penguins?  http://www.cheesemans.com/southgeorgia


Ted Cheeseman
teo@cheesemans.com
http://www.cheesemans.com

Cheesemans' Ecology Safaris
20800 Kittridge Rd.
Saratoga, CA  95070
408-741-5330

Do you like Cheesemans' Ecology Safaris?: http://on.fb.me/hF9iTR

**Comment by vrooje** [comment] 2015-08-18 13:07
Hmm, this isn't happening (so far) for GZ Bars.

**Comment by camallen** [comment] 2015-09-02 08:59
i think this will be fixed by #1310

**Closed by camallen** 2015-09-02 08:59 UTC

**Comment by mschwamb** [comment] 2015-10-09 13:56
This just happened for me today. The email was received at 4pm Taiwan time today and it's now 9:56pm taiwan time.

**Comment by camallen** [comment] 2015-10-09 13:59
this could be linked to long export generation times.

**Comment by mschwamb** [comment] 2015-10-09 14:07
Hadn't realized this said classifications, I had exported the subjects, but that could still haven taken some time. I don't remember exactly what time I hit the button for this instance.
