### ISSUE TITLE
"Error: Cellect is unavailable"

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#729] opened 2015-03-31 20:46 UTC
I am trying out Project "Season Spotter Alpha3"
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season+Spotter+Alpha3
and when I click on a Workflow to load Subjects, I get the error message:
```
Error: Cellect is unavailable
```
I do not have this trouble with very similar projects. For example:
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season+Spotter+Mu2
(select Workflow "4_ComplexAMOS")
works fine.

The only major difference between these two projects is that the former has almost 200 subjects and the latter has just 10.

Both projects are private=false, so you should be able to try them out.

**Comment by edpaget** [comment] 2015-03-31 21:04
Looks like the issue is that Cellect can't load the Workflow quickly enough and the task gets killed.

**Comment by mkosmala** [comment] 2015-04-01 00:00
@edpaget Can you prioritize this bug? I'm read to do alpha testing, but can't do it if subjects don't load.

**Comment by camallen** [comment] 2015-04-01 10:45
It was a DB error in Cellect-Panoptes, I've restarted manually and it resolved the issue. Possibly related to https://github.com/zooniverse/cellect_panoptes/issues/24 but could have been related to post stargazing infrastructure changes. 

Closing for now, will revisit if we can reproduce on demand.

**Closed by camallen** 2015-04-01 10:45 UTC
Labels: bug
