### ISSUE TITLE
Cap Lengths of description fields

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1043] opened 2015-06-29 20:00 UTC
Now we now what the design of the site will work, we should probably cap the lengths of some of the project fields so they fit within the page. 

How longs should 
+ description
+ title
+ workflow_description
+ introduction

be? @brian-c @DarrenMcRoy @heathv

**Comment by DarrenMcRoy** [comment] 2015-07-01 14:38
This is a duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/758 -- close one or the other?

**Comment by brian-c** [comment] 2015-07-01 14:57
Design should fit the content, not the other way around. There are probably reasonable limits to put on these, but we shouldn't decide them based on what the site looks like right now.

**Comment by camallen** [comment] 2015-07-14 14:24
agree we should have reasonable limits to stop essay's being written that the api has to serialize and the UI has to present somehow. Not sure what these are though as i'm sure edge cases will come along.

**Comment by edpaget** [comment] 2015-07-16 15:03
Based on data that exists in staging and production right now I'm going to do with the following limits: 

* Description: 300 Characters (longest is 220)
* Title: 255 Characters (already the limit of the varchar field)
* Workflow_description: 500 Characters (longest is 200)
* Introduction: 1500 Characters (longest is 1200)

**Comment by camallen** [comment] 2015-07-16 15:05
looks good to me.

**Closed** 2015-07-16 16:11 UTC
