### ISSUE TITLE
Add feature flag to remove seens / retired stripping after selection

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1988] opened 2016-09-30 11:27 UTC
We can add a feature flag to modify the subject selection code paths at runtime to avoid the load that  stripping the seen / retired ids as this is effectively running the same set of queries twice (once during selection and once after). During peak loads (stargazing) we may want the ability to turn this off dynamically. 

Selection should not normally return seen / retired data but it can do under certain circumstances.
1. Delayed seen creation with backed up sidekiq / redis down
2. Cellect doesn't have the latest seen information / retired set
3. Race condition between retiring / marking seen and selection running

**Comment by zwolf** [comment] 2017-03-15 21:46
Duplicate of https://github.com/zooniverse/Panoptes/pull/2227

**Closed** 2017-03-15 21:46 UTC
Labels: enhancement
