### ISSUE TITLE
Subjects are not served randomly

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1158] opened 2015-07-21 01:50 UTC
Hey @camallen @edpaget, I'm not signed in, and trying out one of my workflows as an anonymous user. It has 5890 subjects. However, when I start, I'm only getting served images in the first 91 subjects (which are all from the same site). I'm up to ten in a row now -- seems a bit unlikely for a supposedly randomized draw. This is boring! What's going on?

**Comment by aliburchard** [comment] 2015-07-21 09:03
is this an issue with #1141 ?

**Comment by camallen** [comment] 2015-07-21 09:38
I can't reproduce and most likely fixed by #1141 when we got that deployed. @mkosmala please reopen with more details (network logs from the browser, etc) if this is still a problem.

**Closed by camallen** 2015-07-21 09:38 UTC

**Comment by mkosmala** [comment] 2015-07-21 14:53
@camallen Looks like it's fixed now. But interestingly, the subjects grabbed in one batch (10? 20?) are shown to the user in ID order. Would be even better if the order within the batch was randomized, too, if that's not too difficult. (But the major issue of filling the batch randomly from the whole set of subjects is fixed.)

**Comment by camallen** [comment] 2015-07-21 15:02
yeah - i think that's an an issue with the way we serialze our responses, it's not a simple fix right now.

**Comment by mkosmala** [comment] 2015-07-21 15:27
Ok. I'll make and issue for it, and you can mark it as low priority.
