### ISSUE TITLE
New password error

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes#1106] opened 2015-07-14 11:00 UTC
Not sure if this is the place to post, but I cam across this this morning at around 10am on Windows 7 and most recent Chrome browser as well as my mac.
![image](https://cloud.githubusercontent.com/assets/6482891/8671787/f32b8f30-2a1f-11e5-8fbe-f72ddeae8558.png)

**Comment by camallen** [comment] 2015-07-14 11:04
Hmm - just test on my account and it worked fine. @VVH can you reset your password via the frontend on your computer? If so then this might be a windows error on the front end.

**Comment by camallen** [comment] 2015-07-15 13:21
@VVH can you please reproduce somehow?

**Comment by camallen** [comment] 2015-07-20 11:07
closing - please reopen if you can reproduce.

**Comment by camallen** [comment] 2015-07-21 09:49
Looks like this is a duplicate form submission after they've reset their password but the page doesn't redirect / change so they press submit again.

**Closed** 2015-07-21 09:50 UTC
