### ISSUE TITLE
data export bug - unexpected annotation for given workflow

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/Panoptes#2491] opened 2017-10-12 13:54 UTC
Matt from Mutual Muses (https://www.zooniverse.org/projects/melissaagill/mutual-muses) team writes: 
 
> Our latest data export contained an unexpected bug: I had filtered the classifications based on a specific workflow version – 5.17. All the JSON from the “annotations” column was formatted as expected for that workflow… save for one single classification ID – 73150258 – which contained annotation data that I would have expected for one of the other workflows that we have used for our subjects.
>  
> This was totally unexpected behavior for the data export, which has usually had a good, predictable format – I suspect it might be a bug in the Zooniverse data export system. Would you be able to pass this along to the support team?

**Comment by CKrawczyk** [comment] 2017-10-12 14:52
I saw a similar thing happen with the Galaxy Zoo: 3D data dumps, about 3 classifications were saved with the wrong workflow ID (or at the very least were formatted as classifications from a different workflow).

**Comment by srallen** [comment] 2017-10-12 14:55
I think we identified a caching bug with workflow selection in the past that is caused by the panoptes-javascript-client. Are this incorrect annotations for the classification from signed out users?

**Comment by snblickhan** [comment] 2017-10-12 14:56
@srallen he didn't say in his original email. Want me to put you in touch if you need more info?

**Comment by srallen** [comment] 2017-10-12 14:59
@snblickhan we can look it up since we have the classification id for the Mutual Muses case. My question is also for @CKrawczyk. I think the past example was with one of Meg's projects and it was with a signed out user. If that's true for these cases too, then I think my hypothesis on what the issue is may be accurate and we'll have an idea on what to debug. I'm pretty sure this is a front-end bug rather than an export or Panoptes bug.

**Comment by CKrawczyk** [comment] 2017-10-12 15:27
I will dig through my data tomorrow and let you know.

**Comment by camallen** [comment] 2017-11-07 14:06
closing this for now, though happy to re-open. 

This appears that the UI is submitting the wrong workflow id. Currently there isn't much the backend can do to test the annotations match the expected workflow tasks so we can't distinguish if it's valid, we trust the clients. 

Best to filter these out in the dumps or we move / mark them manually in the backend.

**Closed by camallen** 2017-11-07 14:06 UTC
