### ISSUE TITLE
nonrandom subject queing

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#1033] opened 2015-06-26 14:17 UTC
On an ouroboros project, if I refresh the page without classifying, I am served a new image every time.

On Panoptes (specifically http://preview.zooniverse.org/panoptes/#/projects/aliburchard/wildebeest-watch), if I refresh the page without classifying, I am presented with the same image. Even if I close the tab and open a new tab and go to the wildebeest watch landing page, I am ultimately presented with the same image. This happens until I submit a complete classification for the subject in question.

**Comment by marten** [comment] 2015-06-26 14:21
I think this is by design. Panoptes maintains a queue of subjects per user per subject set. Not sure if it's mainly for performance reasons (selecting randomly from large sets can take a while, so having a cached queue of -- I think -- 50 subjects speeds things greatly).

So the subjects are chosen randomly, just not for every reload.

That said, I don't mean to imply "by design" can't change.

**Comment by camallen** [comment] 2015-06-26 14:26
Yeah that's a feature, the idea is to get the user to submit an answer on each subject. 

Non-logged in users get a random sample from the non-logged in queue. Logged in users get the list as is, details [here](https://github.com/zooniverse/Panoptes/blob/438d16231c60cbeed1156d0ffa602ca1f4222eb6/app/models/subject_queue.rb#L103).

**Comment by edpaget** [comment] 2015-06-26 14:39
Yeah I think if we want to let users skip they should have to explicitly click a button to do so. That way we can track what people skip which we can't do now.

**Comment by edpaget** [comment] 2015-06-26 14:39
(also I've always wanted to label something wontfix sorry ali)

**Comment by aliburchard** [comment] 2015-06-26 14:47
That makes sense. No problem :)

**Comment by aliburchard** [comment] 2015-06-29 10:39
Sorry @edpaget there's something still going on. I realize you guys are caching photos for serving to users, but the photos in my cache are not selected randomly. I'm getting a series of photos in order from the same camera trap in a row, so they had to have been selected from the manifest in a batch.

Are we not randomly selecting photos to serve to users from the entire subject set? Or are we just working down the manifest in order? The second one will be a big problem (for me, and likely many others...)

**Comment by camallen** [comment] 2015-06-29 10:55
Selection comes from the queue, the queue is built using 100 randomly selected photos. Which project are you getting the problem on? Is this happening across all projects?

**Comment by aliburchard** [comment] 2015-06-29 10:57
I don't know how the whales subjects were uploaded. I'm getting it on Wildebeest watch.

**Comment by edpaget** [comment] 2015-06-29 14:27
Subjects should be selected randomly. There are numerous things that could cause you too the behaviour your seeing though (such as classifying while subjects are still uploading). Do you still see subjects in the same order if you classify logged out or with a different user?

**Comment by camallen** [comment] 2015-06-29 15:00
I've just checked this out. My understanding is data is selected randomly from the available data, but the available data is ordered by the id so the random selection is over a sorted set. I think we need to add an `order by random` clause [here](https://github.com/zooniverse/Panoptes/blob/97af03f71a071f78852c04f812a53fd2dbaad464/lib/postgresql_selection.rb#L48)

**Comment by camallen** [comment] 2015-06-30 14:41
@edpaget if a user uploads their data in order then those returned subject ids should be shuffled like how i linked above.

**Comment by marten** [comment] 2015-07-16 12:41
I'm seeing about 80% of the queues having their subject ids being sorted already. But not sure why, since they seem to come shuffled out of the selection method.

**Closed** 2015-07-16 14:43 UTC
Labels: wontfix
