### ISSUE TITLE
robots and people - what counts as a classification?

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes#1396] opened 2015-09-30 09:24 UTC
I'm seeing that there are some users that might be robots or just unaware of how the process is supposed to work. Here is an example - one user has clicked on nothing and I have a classification entry of "null" for 12992 subjects as a result of that one individual. Do these count towards retirement? Yesterday this individual "classified" over 2000 subjects. 

Should something be added to stop a user if they are clicking through at a rate that is higher than you might expect if they were actually classifying? Should something be added to try alter a user behaviour if they repeatedly are just clicking 'done' on the first question rather than actually answering?

**Comment by vrooje** [comment] 2015-10-08 10:29
We see tourism on just about every project. (You're right that it's not always a bot; I've seen kids do it when I hand them iPads in live demos. They just want to see the pretty pictures.)

There are various ways to downweight these classifiers. Galaxy Zoo uses a consensus-based weighting scheme that calculates how well a classifier agrees with the established consensus for the subjects they've classified, *on average* over all their classifications. A project tourist tends to have a very low consensus score, and then in GZ we apply a weight that strongly downweights very low scores but keeps nearly everyone else at equal weight. 

Other projects have handled it differently. The Milky Way Project weighted classifiers in part by how much they used the interface itself, reasoning that people who spent more time refining their classification were paying more attention and so should get higher weight. You could apply a similar approach here based on the difference between skipping the classification and clicking "nothing to classify". 

I don't think anyone has used a rate cut to select tourists/bots, but it would be interesting to see how well it works. 

We have discussed interventions to encourage tourists to actually engage with classifying, but for now dealing with these classifications is something individual research teams do as appropriate for their project in the post-classification stage. It might be added to the aggregations in the future, but I don't think it's in yet.

**Comment by aliburchard** [comment] 2015-10-08 10:35
Out of curiosity, was this user logged in? Or is the ID based on an IP address/SessionID?

On projects with high rates of tourism, we might want to consider dropping non-logged in users from the aggregation analysis.

**Comment by vrooje** [comment] 2015-10-08 10:38
I believe the original GZ had a very prolific bot, and that project required a login, so I'm not sure that would be enough.

I'm curious what the tourism rate is on Fossil Finder!

**Comment by camallen** [comment] 2015-10-08 10:52
@AdrianEvans re retirement, yes currently all classifications count towards the retirement limit.

**Comment by aliburchard** [comment] 2015-10-08 10:54
A thought (and imperfect solution): Make the first question *required* so users can't submit a null classification.

I know you make sub-tasks *not* required because of https://github.com/zooniverse/Panoptes-Front-End/issues/1563, and that making main tasks required triggers the sort of heavy-handed text on the workflow (see https://github.com/zooniverse/Panoptes-Front-End/issues/1666). But requiring answers would reduce the amount of spam.

**Comment by camallen** [comment] 2015-10-19 10:27
closing this, please reopen if you feel that the issue is still unclear.

**Closed by camallen** 2015-10-19 10:27 UTC
