### ISSUE TITLE
Made a new workflow with a new subject set live and deactivated previous completed subject set and workflow and project page still says 'Great work! Looks like this project is out of data at the moment!'

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2574] opened 2017-12-12 05:08 UTC
I just launched the new P4: Ridges workflow. I activated the new workflow linked to a brand new subject (where all images have not been classified). I then deactivated the old workflow that had the completed subject set. The site still says that there is no data on the site when there is. 

<img width="1084" alt="screen shot 2017-12-12 at 12 05 35 am" src="https://user-images.githubusercontent.com/753325/33868322-4a08c540-ded0-11e7-900c-9a047a4a9bcf.png">

<img width="1088" alt="screen shot 2017-12-12 at 12 05 33 am" src="https://user-images.githubusercontent.com/753325/33868369-79b6d70a-ded0-11e7-9a71-9e40cb7cac57.png">

The site should know that I've set up a new workflow and a new subject set and remove the message

**Comment by mschwamb** [comment] 2017-12-12 05:19
The message just went away, after more than a 10 minute wait. 

<img width="1115" alt="screen shot 2017-12-12 at 12 18 23 am" src="https://user-images.githubusercontent.com/753325/33868627-152a0a76-ded2-11e7-9222-911f0e79edca.png">

Maybe this lag time could be made shorter?

**Comment by camallen** [comment] 2017-12-12 11:25
duplicate of https://github.com/zooniverse/Panoptes/issues/2242.

**Closed by camallen** 2017-12-12 11:25 UTC
