### ISSUE TITLE
Project newsletters for old projects -- do people have to re-opt-in?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes#1247] opened 2015-08-07 20:51 UTC
I'm slightly concerned because I've noticed that it doesn't appear that I am still automatically subscribed to the newsletters for any of the old projects that I've classified on.

For instance, if we send a newsletter to Chicago Wildlife Watch users, is it only going to go to those who have manually resubscribed to it... ? Because that cannot be too many people?

I also checked the "Get email updates from the Projects you classify on" button, and it didn't check off the list below.

And I tried doing a classification on Snapshot Serengeti to make it appear in my list of checkboxes, with the "Get email updates from the Projects you classify on" box checked, and when Snapshot appeared, it was unchecked.

![screen shot 2015-08-07 at 3 43 11 pm](https://cloud.githubusercontent.com/assets/8987864/9145695/38d42e84-3d1c-11e5-8fad-b31fbcf57dfc.png)

Just a bit concerned over whether we've lost track of who is subscribed to what, and if all our users were imported from old projects with empty newsletter settings. What's up there?

**Comment by camallen** [comment] 2015-08-12 16:28
This is related to the stats migration. @mrniaboc will be able to construct lists in the meantime but we need to get this fixed.

> I also checked the "Get email updates from the Projects you classify on" button, and it didn't check off the list below.

This is intended behaviour, this field is used when a user classifies for the first time on a project. if ticked and a user classifies (for the first time) then any subsequent project email preference will be set to true.

>And I tried doing a classification on Snapshot Serengeti to make it appear in my list of checkboxes, with the "Get email updates from the Projects you classify on" box checked, and when Snapshot appeared, it was unchecked.

Yeah this is a gap between the planned migration being run around the cut over period. The current code updates the counts an existing preference for legacy projects. It's not responsible for communication prefs since the canonical version of this should have been migrated.

So we haven't lost track we just haven't consolidated the data. In theory any new modifications to project prefs will have true / false values in panoptes DB. Old communication pref data is in zoo home so we need to combine the two when migrating.

**Comment by edpaget** [comment] 2015-08-17 17:24
Closed by 1279

**Closed by edpaget** 2015-08-17 17:24 UTC
