### ISSUE TITLE
Whitelist staging API

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes#3203] opened 2019-11-20 17:11 UTC
The rebuild staging preview URL needs whitelisting on the staging API: https://frontend.preview.zooniverse.org/ (attempting to login throws a CORS error)

**Comment by camallen** [comment] 2019-11-26 11:30
I believe this was caused by https://github.com/zooniverse/Panoptes/pull/3199 and fixed by https://github.com/zooniverse/front-end-monorepo/pull/1323 please reopen if this is still and issue.

**Closed by camallen** 2019-11-26 11:30 UTC
