### ISSUE TITLE
missing classification (or miscalculation of retirement) ?

### ISSUE THREAD

**Issue by denslowm** [zooniverse/panoptes#3599] opened 2021-05-03 19:50 UTC
Hi, I have reported a similar issue in the past. I have read through those issues and tried the suggested remedies as outlined below. 

Take the following workflow (now completed):
https://www.zooniverse.org/lab/11689/workflows/16896

The associated subject set is:
https://www.zooniverse.org/lab/11689/subject-sets/88501

The retirement limit was set to 3 and the workflow completed (reached 100% retirement) months ago. I doubled checked the stats today and it says 100% retired. I noticed that the export seemed to be missing a single classification for subject 50715191. Today I regenerated the export and I still only see two entries for the subject 50715191. 

It might be notable that both classifications for that subject say `"classifications_count":2` and 
`"retired_at":"2020-11-26T03:50:44.710Z","subject_id":50715191,"retirement_reason":"classification_count"}`

Are we missing a classification? Is retirement not being calculated correctly? Something else?

**Comment by lcjohnso** [comment] 2021-05-17 20:26
Duplicate of #3500 -- closing after investigation showed no systematic pattern in behavior that is actionable.

**Closed by lcjohnso** 2021-05-17 20:26 UTC
