### ISSUE TITLE
Subjects retiring with too few classifications!

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1366] opened 2015-09-14 19:43 UTC
@camallen @edpaget I have a bunch of subjects in Season Spotter Questions that are all marked "retired", but have fewer than 5 classifications. (5 is the set retirement limit.)

For example, check out subject 595581, which has 10 classifications according to the subject export, but only 2 classifications show up in the classifications export.

**Comment by ggdhines** [comment] 2015-09-14 21:57
duplicate of #1363 (really not sure what's going on)

**Comment by marten** [comment] 2015-09-15 11:04
@mkosmala We'll make sure to unretire any falsely retired subjects when we fix this.

**Comment by marten** [comment] 2015-11-30 12:27
@mkosmala the solution we ended up with calculates by counting classifications made since a given date. I have Season Spotter Questions down as 2015-07-21, is that the date you'd want to start the counters (essentially that's then the date they would have all been zero). If so, I'll trigger a recount.

**Comment by mkosmala** [comment] 2015-11-30 15:59
@marten Yep, 2015-07-21 is perfect. For both Season Spotter Questions (project id 347) and Season Spotter Image Marking (id 348).

**Comment by marten** [comment] 2015-11-30 16:28
@mkosmala In that case, everything should be fixed up now. Here's the number of subjects that were dragged out of retirement as a result:

Questions:

* "1-4_SimpleSingleCrops" => 200
* "1-3_SimpleSingleGrass" => 163
* "1-1-5_SimpleSingleShrubs" => 211
* "1-2_SimpleSingleNeedleleafTrees" => 167
* "1-1_SimpleSingleBroadleafTrees" => 179
* "2-2_SimpleDoubleDeciduousFall" => 152
* "2-1_SimpleDoubleDeciduousSpring" =>156

Image Marking:

* "3-2_ComplexTrees" => 0
* "5_ComplexShifts" => 3
* "4_ComplexAMOS" => 2

**Closed by marten** 2015-11-30 16:28 UTC
